{{- if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}-{{ .Values.color }}
  labels:
    app: {{ .Values.name }}
    color: {{ .Values.color }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
      color: {{ .Values.color }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
        color: {{ .Values.color }}
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: Always
        {{- if .Values.container.command }}
        command:
          {{- toYaml .Values.container.command | nindent 10 }}
        {{- end }}
        {{- if .Values.container.args }}
        args:
          {{- toYaml .Values.container.args | nindent 10 }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.ports.container }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: {{ .Values.ports.container }}
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /healthz
            port: {{ .Values.ports.container }}
          initialDelaySeconds: 10
          periodSeconds: 10
        env:
        - name: APP_NAME
          value: {{ .Values.name | quote }}
        - name: APP_COLOR
          value: {{ .Values.color | quote }}
        - name: APP_SERVICE_PORT
          value: {{ .Values.ports.service | quote }}
        resources:
{{- if .Values.resources }}
{{ toYaml .Values.resources | indent 10 }}
{{- else }}
          {}
{{- end }}
        
      {{- if .Values.nodeAffinity.enabled }}
      affinity:
        nodeAffinity:
          {{- if .Values.nodeAffinity.required.values }}
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: {{ .Values.nodeAffinity.required.key | quote }}
                operator: In
                values:
{{ toYaml .Values.nodeAffinity.required.values | indent 16 }}
          {{- end }}
          {{- if .Values.nodeAffinity.preferred }}
          preferredDuringSchedulingIgnoredDuringExecution:
{{- range .Values.nodeAffinity.preferred }}
          - weight: {{ .weight }}
            preference:
              matchExpressions:
              - key: {{ .key | quote }}
                operator: In
                values:
{{ toYaml .values | indent 16 }}
{{- end }}
          {{- end }}
      {{- end }}

      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}

      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
{{- with .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
